version: '2'
services:
  broker-2:
    image: confluentinc/cp-kafka:4.0.0
    container_name: broker-2
    extra_hosts:
      - "zookeeper_1:192.168.16.10"
      - "zookeeper_2:192.168.16.20"
      - "zookeeper_3:192.168.16.30"
    env_file:
      - ./kafka-broker-2.env
    ports:
      - 29092:29092
    volumes:
      - /home/ubuntu/kafka/broker_2/data:/var/lib/kafka/data
