version: '2'
services:
  broker-2:
    image: confluentinc/cp-kafka:4.0.0
    container_name: broker-2
    extra_hosts:
      - "zookeeper_1:172.31.32.10"
      - "zookeeper_2:172.31.0.10"
      - "zookeeper_3:172.31.80.10"
    env_file:
      - ./kafka-broker-2.env
    ports:
      - 29092:29092
    volumes:
      - /home/ubuntu/kafka/broker_2/data:/var/lib/kafka/data
