version: '2'
services:
  schema-registry-2:
    image: confluentinc/cp-schema-registry:4.0.0
    container_name: schema-registry-2
    extra_hosts:
      - "zookeeper_1:172.31.32.10"
      - "zookeeper_2:172.31.0.10"
      - "zookeeper_3:172.31.80.10"
    env_file:
      - ./schema-registry-2.env
    ports:
      - 7070:7070

