version: '2'
services:
  zookeeper-2:
    image: confluentinc/cp-zookeeper:4.0.0
    container_name: zookeeper-2
    extra_hosts:
      - "zookeeper_1:172.31.32.10"
      - "zookeeper_2:172.31.0.10"
      - "zookeeper_3:172.31.80.10"
    env_file:
      - ./zookeeper-2.env
    ports:
      - 32181:32181
      - 32888:32888
      - 33888:33888
    volumes:
      - /home/ubuntu/zookeeper_2/data:/var/lib/zookeeper/data
      - /home/ubuntu/zookeeper_2/logs:/var/lib/zookeeper/log

